version: '3.8'
services:
  nginx:
    image: 'nginx:1.21'
    container_name: note-nginx
    ports:
      - '80:80'
    volumes:
      - '../:/var/www'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/sites/:/etc/nginx/sites-available'
      - './docker/nginx/logs:/var/log/nginx'
    working_dir: /var/www
    links:
      - app
  app:
    build:
      context: docker/app
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: note-app
    volumes:
      - '../:/var/www'
      - './docker/app/logs:/var/log/php-fpm'
      - './docker/app/php-ini-overrides.ini:/usr/local/etc/php/conf.d/40-custom.ini'
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal idekey=PHPSTORM start_with_request=yes
      PHP_IDE_CONFIG: serverName=Docker
    extra_hosts:
      - host.docker.internal:host-gateway
    working_dir: /var/www
    links:
      - pg
      - redis
  pg:
    image: 'postgres:14'
    container_name: note-pg
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRESQL_MAX_OPEN_CONNS: 2000
    volumes:
      - './database/pg:/var/lib/postgresql/data'
      - './temp:/temp'
  redis:
    image: redis
    container_name: note-redis
    ports:
      - '6379:6379'
    volumes:
      - './database/redis:/data'